version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aATHIF123#
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  service-registry:
    image: service-registry-image
    container_name: service-registry
    restart: always
    ports:
      - "8761:8761"
    depends_on:
      - postgres

  api-gateway:
    image: api-gateway-image
    container_name: api-gateway
    restart: always
    ports:
      - "8765:8765"
    depends_on:
      - service-registry

  user-service:
    image: user-service-image
    container_name: user-service
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - service-registry

  learner-service:
    image: learner-service-image
    container_name: learner-service
    restart: always
    ports:
      - "8090:8090"
    depends_on:
      - postgres
      - service-registry

  instructor-service:
    image: instructor-service-image
    container_name: instructor-service
    restart: always
    ports:
      - "8098:8098"
    depends_on:
      - postgres
      - service-registry

  course-service:
    image: course-service-image
    container_name: course-service
    restart: always
    ports:
      - "8091:8091"
    depends_on:
      - postgres
      - service-registry

  finance-service:
    image: finance-service-image
    container_name: finance-service
    restart: always
    ports:
      - "8092:8092"
    depends_on:
      - postgres
      - service-registry

volumes:
  postgres-data:
